# Generated by Django 4.2.2 on 2024-09-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_username_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ethereum_wallet_address',
            field=models.CharField(default=151468012026108026269076037154149813776070056589, max_length=42),
            preserve_default=False,
        ),
    ]
